language: php
install: skip
before_script: skip
script: skip
deploy:
    provider: script
    script:
        - cd src
        - find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://$FTP_ADDRESS/{} \\;
    on:
        branch: master
